// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zahif.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BatchIndexRequest struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	IndexIdentifier      string   `protobuf:"bytes,2,opt,name=index_identifier,json=indexIdentifier,proto3" json:"index_identifier,omitempty"`
	ExcludePatterns      []string `protobuf:"bytes,3,rep,name=exclude_patterns,json=excludePatterns,proto3" json:"exclude_patterns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchIndexRequest) Reset()         { *m = BatchIndexRequest{} }
func (m *BatchIndexRequest) String() string { return proto.CompactTextString(m) }
func (*BatchIndexRequest) ProtoMessage()    {}
func (*BatchIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0540cc00153485a, []int{0}
}

func (m *BatchIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchIndexRequest.Unmarshal(m, b)
}
func (m *BatchIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchIndexRequest.Marshal(b, m, deterministic)
}
func (m *BatchIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchIndexRequest.Merge(m, src)
}
func (m *BatchIndexRequest) XXX_Size() int {
	return xxx_messageInfo_BatchIndexRequest.Size(m)
}
func (m *BatchIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchIndexRequest proto.InternalMessageInfo

func (m *BatchIndexRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *BatchIndexRequest) GetIndexIdentifier() string {
	if m != nil {
		return m.IndexIdentifier
	}
	return ""
}

func (m *BatchIndexRequest) GetExcludePatterns() []string {
	if m != nil {
		return m.ExcludePatterns
	}
	return nil
}

type BatchIndexResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchIndexResponse) Reset()         { *m = BatchIndexResponse{} }
func (m *BatchIndexResponse) String() string { return proto.CompactTextString(m) }
func (*BatchIndexResponse) ProtoMessage()    {}
func (*BatchIndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0540cc00153485a, []int{1}
}

func (m *BatchIndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchIndexResponse.Unmarshal(m, b)
}
func (m *BatchIndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchIndexResponse.Marshal(b, m, deterministic)
}
func (m *BatchIndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchIndexResponse.Merge(m, src)
}
func (m *BatchIndexResponse) XXX_Size() int {
	return xxx_messageInfo_BatchIndexResponse.Size(m)
}
func (m *BatchIndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchIndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchIndexResponse proto.InternalMessageInfo

type IndexProgressRequest struct {
	IndexIdentifier      string   `protobuf:"bytes,1,opt,name=index_identifier,json=indexIdentifier,proto3" json:"index_identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexProgressRequest) Reset()         { *m = IndexProgressRequest{} }
func (m *IndexProgressRequest) String() string { return proto.CompactTextString(m) }
func (*IndexProgressRequest) ProtoMessage()    {}
func (*IndexProgressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0540cc00153485a, []int{2}
}

func (m *IndexProgressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexProgressRequest.Unmarshal(m, b)
}
func (m *IndexProgressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexProgressRequest.Marshal(b, m, deterministic)
}
func (m *IndexProgressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexProgressRequest.Merge(m, src)
}
func (m *IndexProgressRequest) XXX_Size() int {
	return xxx_messageInfo_IndexProgressRequest.Size(m)
}
func (m *IndexProgressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexProgressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndexProgressRequest proto.InternalMessageInfo

func (m *IndexProgressRequest) GetIndexIdentifier() string {
	if m != nil {
		return m.IndexIdentifier
	}
	return ""
}

type IndexProgressResponse struct {
	PercentageDone       float32  `protobuf:"fixed32,1,opt,name=percentage_done,json=percentageDone,proto3" json:"percentage_done,omitempty"`
	IndexedDocuments     int32    `protobuf:"varint,2,opt,name=indexed_documents,json=indexedDocuments,proto3" json:"indexed_documents,omitempty"`
	TotalDocuments       int32    `protobuf:"varint,3,opt,name=total_documents,json=totalDocuments,proto3" json:"total_documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexProgressResponse) Reset()         { *m = IndexProgressResponse{} }
func (m *IndexProgressResponse) String() string { return proto.CompactTextString(m) }
func (*IndexProgressResponse) ProtoMessage()    {}
func (*IndexProgressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0540cc00153485a, []int{3}
}

func (m *IndexProgressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexProgressResponse.Unmarshal(m, b)
}
func (m *IndexProgressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexProgressResponse.Marshal(b, m, deterministic)
}
func (m *IndexProgressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexProgressResponse.Merge(m, src)
}
func (m *IndexProgressResponse) XXX_Size() int {
	return xxx_messageInfo_IndexProgressResponse.Size(m)
}
func (m *IndexProgressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexProgressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IndexProgressResponse proto.InternalMessageInfo

func (m *IndexProgressResponse) GetPercentageDone() float32 {
	if m != nil {
		return m.PercentageDone
	}
	return 0
}

func (m *IndexProgressResponse) GetIndexedDocuments() int32 {
	if m != nil {
		return m.IndexedDocuments
	}
	return 0
}

func (m *IndexProgressResponse) GetTotalDocuments() int32 {
	if m != nil {
		return m.TotalDocuments
	}
	return 0
}

type SearchIndexRequest struct {
	IndexIdentifier      string   `protobuf:"bytes,1,opt,name=index_identifier,json=indexIdentifier,proto3" json:"index_identifier,omitempty"`
	Query                string   `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchIndexRequest) Reset()         { *m = SearchIndexRequest{} }
func (m *SearchIndexRequest) String() string { return proto.CompactTextString(m) }
func (*SearchIndexRequest) ProtoMessage()    {}
func (*SearchIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0540cc00153485a, []int{4}
}

func (m *SearchIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchIndexRequest.Unmarshal(m, b)
}
func (m *SearchIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchIndexRequest.Marshal(b, m, deterministic)
}
func (m *SearchIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchIndexRequest.Merge(m, src)
}
func (m *SearchIndexRequest) XXX_Size() int {
	return xxx_messageInfo_SearchIndexRequest.Size(m)
}
func (m *SearchIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchIndexRequest proto.InternalMessageInfo

func (m *SearchIndexRequest) GetIndexIdentifier() string {
	if m != nil {
		return m.IndexIdentifier
	}
	return ""
}

func (m *SearchIndexRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchIndexRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchIndexRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type SearchIndexResponse struct {
	Documents            []string `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchIndexResponse) Reset()         { *m = SearchIndexResponse{} }
func (m *SearchIndexResponse) String() string { return proto.CompactTextString(m) }
func (*SearchIndexResponse) ProtoMessage()    {}
func (*SearchIndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0540cc00153485a, []int{5}
}

func (m *SearchIndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchIndexResponse.Unmarshal(m, b)
}
func (m *SearchIndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchIndexResponse.Marshal(b, m, deterministic)
}
func (m *SearchIndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchIndexResponse.Merge(m, src)
}
func (m *SearchIndexResponse) XXX_Size() int {
	return xxx_messageInfo_SearchIndexResponse.Size(m)
}
func (m *SearchIndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchIndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchIndexResponse proto.InternalMessageInfo

func (m *SearchIndexResponse) GetDocuments() []string {
	if m != nil {
		return m.Documents
	}
	return nil
}

type DeleteIndexRequest struct {
	IndexIdentifier      string   `protobuf:"bytes,1,opt,name=index_identifier,json=indexIdentifier,proto3" json:"index_identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteIndexRequest) Reset()         { *m = DeleteIndexRequest{} }
func (m *DeleteIndexRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteIndexRequest) ProtoMessage()    {}
func (*DeleteIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0540cc00153485a, []int{6}
}

func (m *DeleteIndexRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteIndexRequest.Unmarshal(m, b)
}
func (m *DeleteIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteIndexRequest.Marshal(b, m, deterministic)
}
func (m *DeleteIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteIndexRequest.Merge(m, src)
}
func (m *DeleteIndexRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteIndexRequest.Size(m)
}
func (m *DeleteIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteIndexRequest proto.InternalMessageInfo

func (m *DeleteIndexRequest) GetIndexIdentifier() string {
	if m != nil {
		return m.IndexIdentifier
	}
	return ""
}

type DeleteIndexResponse struct {
	PercentageDone       int32    `protobuf:"varint,1,opt,name=percentage_done,json=percentageDone,proto3" json:"percentage_done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteIndexResponse) Reset()         { *m = DeleteIndexResponse{} }
func (m *DeleteIndexResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteIndexResponse) ProtoMessage()    {}
func (*DeleteIndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0540cc00153485a, []int{7}
}

func (m *DeleteIndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteIndexResponse.Unmarshal(m, b)
}
func (m *DeleteIndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteIndexResponse.Marshal(b, m, deterministic)
}
func (m *DeleteIndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteIndexResponse.Merge(m, src)
}
func (m *DeleteIndexResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteIndexResponse.Size(m)
}
func (m *DeleteIndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteIndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteIndexResponse proto.InternalMessageInfo

func (m *DeleteIndexResponse) GetPercentageDone() int32 {
	if m != nil {
		return m.PercentageDone
	}
	return 0
}

func init() {
	proto.RegisterType((*BatchIndexRequest)(nil), "proto.BatchIndexRequest")
	proto.RegisterType((*BatchIndexResponse)(nil), "proto.BatchIndexResponse")
	proto.RegisterType((*IndexProgressRequest)(nil), "proto.IndexProgressRequest")
	proto.RegisterType((*IndexProgressResponse)(nil), "proto.IndexProgressResponse")
	proto.RegisterType((*SearchIndexRequest)(nil), "proto.SearchIndexRequest")
	proto.RegisterType((*SearchIndexResponse)(nil), "proto.SearchIndexResponse")
	proto.RegisterType((*DeleteIndexRequest)(nil), "proto.DeleteIndexRequest")
	proto.RegisterType((*DeleteIndexResponse)(nil), "proto.DeleteIndexResponse")
}

func init() {
	proto.RegisterFile("zahif.proto", fileDescriptor_b0540cc00153485a)
}

var fileDescriptor_b0540cc00153485a = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0xc5, 0x50, 0x53, 0x31, 0xa8, 0x7c, 0x2c, 0xb4, 0x72, 0x5d, 0x0e, 0x68, 0x2f, 0x6d, 0x55,
	0x89, 0x43, 0xb9, 0xb7, 0x2a, 0x45, 0x95, 0x90, 0x7a, 0x40, 0xce, 0x8d, 0x0b, 0x72, 0xec, 0x31,
	0x58, 0x32, 0xb6, 0xb3, 0xbb, 0x48, 0x24, 0xb7, 0x28, 0xff, 0x21, 0x3f, 0x22, 0xbf, 0x32, 0xf6,
	0x7a, 0xb1, 0x0d, 0x58, 0x51, 0x94, 0xd3, 0x6a, 0xde, 0x3c, 0xbf, 0x9d, 0x9d, 0xf7, 0x0c, 0xed,
	0x3b, 0x7b, 0xeb, 0x7b, 0x93, 0x98, 0x45, 0x22, 0x22, 0xba, 0x3c, 0xe8, 0xbd, 0x06, 0xfd, 0x99,
	0x2d, 0x9c, 0xed, 0x22, 0x74, 0xf1, 0x60, 0xe1, 0xcd, 0x1e, 0xb9, 0x20, 0x9f, 0xa0, 0x29, 0x6c,
	0xb6, 0x41, 0x61, 0x68, 0x63, 0xed, 0x5b, 0xcb, 0x52, 0x15, 0xf9, 0x0e, 0x3d, 0x3f, 0xe5, 0xad,
	0x7d, 0x17, 0x43, 0xe1, 0x7b, 0x3e, 0x32, 0xa3, 0x2e, 0x19, 0x5d, 0x89, 0x2f, 0x72, 0x38, 0xa5,
	0xe2, 0xc1, 0x09, 0xf6, 0x2e, 0xae, 0x63, 0x5b, 0x08, 0x64, 0x21, 0x37, 0x1a, 0xe3, 0x46, 0x4a,
	0x55, 0xf8, 0x52, 0xc1, 0x74, 0x08, 0xa4, 0x3c, 0x02, 0x8f, 0xa3, 0x90, 0x23, 0xfd, 0x03, 0x43,
	0x09, 0x2c, 0x59, 0xb4, 0x61, 0xc8, 0xf9, 0x71, 0xb6, 0xaa, 0x19, 0xb4, 0xca, 0x19, 0xe8, 0xa3,
	0x06, 0x1f, 0xcf, 0x34, 0x32, 0x71, 0xf2, 0x15, 0xba, 0x31, 0x32, 0x27, 0x61, 0xda, 0x1b, 0x5c,
	0xbb, 0x51, 0x88, 0x52, 0xa3, 0x6e, 0x75, 0x0a, 0x78, 0x9e, 0xa0, 0xe4, 0x07, 0xf4, 0xa5, 0x2a,
	0xba, 0x09, 0xcb, 0xd9, 0xef, 0x92, 0x16, 0x97, 0x4f, 0xd6, 0xad, 0x9e, 0x6a, 0xcc, 0x8f, 0x78,
	0xaa, 0x2a, 0x22, 0x61, 0x07, 0x25, 0x6a, 0x43, 0x52, 0x3b, 0x12, 0xce, 0x89, 0xf4, 0x41, 0x03,
	0x72, 0x85, 0x36, 0x3b, 0x5b, 0xfb, 0xeb, 0x9f, 0x46, 0x86, 0xa0, 0x27, 0xdf, 0xb0, 0x5b, 0xb5,
	0xfe, 0xac, 0x48, 0xd1, 0xc0, 0xdf, 0xf9, 0x42, 0x5d, 0x9b, 0x15, 0xa9, 0x9b, 0x91, 0xe7, 0xf1,
	0xc4, 0xcd, 0x77, 0x12, 0x56, 0x15, 0x9d, 0xc2, 0xe0, 0x64, 0x08, 0xb5, 0x9b, 0x11, 0xb4, 0x8a,
	0xf9, 0x35, 0x69, 0x59, 0x01, 0xd0, 0xdf, 0x40, 0xe6, 0x18, 0xa0, 0xc0, 0x37, 0x4e, 0x4e, 0x7f,
	0xc1, 0xe0, 0x44, 0xe0, 0x65, 0x47, 0xf4, 0x73, 0x47, 0x7e, 0x3e, 0xd5, 0x41, 0x5f, 0xa5, 0x41,
	0x26, 0x7f, 0x01, 0x8a, 0xdc, 0x10, 0x23, 0x0b, 0xf6, 0xe4, 0x22, 0xcd, 0xe6, 0xe7, 0x8a, 0x8e,
	0x0a, 0x59, 0x8d, 0xfc, 0x87, 0x0f, 0x27, 0x11, 0x21, 0x5f, 0x14, 0xbb, 0x2a, 0x7c, 0xe6, 0xa8,
	0xba, 0x99, 0xab, 0xfd, 0x83, 0x76, 0xe9, 0x71, 0xe4, 0x78, 0xf3, 0xe5, 0xc6, 0x4c, 0xb3, 0xaa,
	0x55, 0xd6, 0x29, 0x59, 0x93, 0xeb, 0x5c, 0x66, 0x26, 0xd7, 0xa9, 0x70, 0x92, 0xd6, 0x66, 0xef,
	0x57, 0xd9, 0x7f, 0x7e, 0xdd, 0x94, 0xc7, 0xf4, 0x39, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x80, 0x7a,
	0x09, 0x04, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ZahifClient is the client API for Zahif service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ZahifClient interface {
	BatchIndex(ctx context.Context, in *BatchIndexRequest, opts ...grpc.CallOption) (*BatchIndexResponse, error)
	IndexProgress(ctx context.Context, in *IndexProgressRequest, opts ...grpc.CallOption) (*IndexProgressResponse, error)
	DeleteIndex(ctx context.Context, in *DeleteIndexRequest, opts ...grpc.CallOption) (*DeleteIndexResponse, error)
	SearchIndex(ctx context.Context, in *SearchIndexRequest, opts ...grpc.CallOption) (*SearchIndexResponse, error)
}

type zahifClient struct {
	cc grpc.ClientConnInterface
}

func NewZahifClient(cc grpc.ClientConnInterface) ZahifClient {
	return &zahifClient{cc}
}

func (c *zahifClient) BatchIndex(ctx context.Context, in *BatchIndexRequest, opts ...grpc.CallOption) (*BatchIndexResponse, error) {
	out := new(BatchIndexResponse)
	err := c.cc.Invoke(ctx, "/proto.Zahif/BatchIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zahifClient) IndexProgress(ctx context.Context, in *IndexProgressRequest, opts ...grpc.CallOption) (*IndexProgressResponse, error) {
	out := new(IndexProgressResponse)
	err := c.cc.Invoke(ctx, "/proto.Zahif/IndexProgress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zahifClient) DeleteIndex(ctx context.Context, in *DeleteIndexRequest, opts ...grpc.CallOption) (*DeleteIndexResponse, error) {
	out := new(DeleteIndexResponse)
	err := c.cc.Invoke(ctx, "/proto.Zahif/DeleteIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zahifClient) SearchIndex(ctx context.Context, in *SearchIndexRequest, opts ...grpc.CallOption) (*SearchIndexResponse, error) {
	out := new(SearchIndexResponse)
	err := c.cc.Invoke(ctx, "/proto.Zahif/SearchIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZahifServer is the server API for Zahif service.
type ZahifServer interface {
	BatchIndex(context.Context, *BatchIndexRequest) (*BatchIndexResponse, error)
	IndexProgress(context.Context, *IndexProgressRequest) (*IndexProgressResponse, error)
	DeleteIndex(context.Context, *DeleteIndexRequest) (*DeleteIndexResponse, error)
	SearchIndex(context.Context, *SearchIndexRequest) (*SearchIndexResponse, error)
}

// UnimplementedZahifServer can be embedded to have forward compatible implementations.
type UnimplementedZahifServer struct {
}

func (*UnimplementedZahifServer) BatchIndex(ctx context.Context, req *BatchIndexRequest) (*BatchIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchIndex not implemented")
}
func (*UnimplementedZahifServer) IndexProgress(ctx context.Context, req *IndexProgressRequest) (*IndexProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IndexProgress not implemented")
}
func (*UnimplementedZahifServer) DeleteIndex(ctx context.Context, req *DeleteIndexRequest) (*DeleteIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteIndex not implemented")
}
func (*UnimplementedZahifServer) SearchIndex(ctx context.Context, req *SearchIndexRequest) (*SearchIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchIndex not implemented")
}

func RegisterZahifServer(s *grpc.Server, srv ZahifServer) {
	s.RegisterService(&_Zahif_serviceDesc, srv)
}

func _Zahif_BatchIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZahifServer).BatchIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Zahif/BatchIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZahifServer).BatchIndex(ctx, req.(*BatchIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zahif_IndexProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZahifServer).IndexProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Zahif/IndexProgress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZahifServer).IndexProgress(ctx, req.(*IndexProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zahif_DeleteIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZahifServer).DeleteIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Zahif/DeleteIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZahifServer).DeleteIndex(ctx, req.(*DeleteIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zahif_SearchIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZahifServer).SearchIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Zahif/SearchIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZahifServer).SearchIndex(ctx, req.(*SearchIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Zahif_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Zahif",
	HandlerType: (*ZahifServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchIndex",
			Handler:    _Zahif_BatchIndex_Handler,
		},
		{
			MethodName: "IndexProgress",
			Handler:    _Zahif_IndexProgress_Handler,
		},
		{
			MethodName: "DeleteIndex",
			Handler:    _Zahif_DeleteIndex_Handler,
		},
		{
			MethodName: "SearchIndex",
			Handler:    _Zahif_SearchIndex_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zahif.proto",
}
