root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/zahif cmd/zahif/zahif.go"
bin = "tmp/zahif"
full_bin = "./tmp/zahif"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]
include_dir = []
exclude_file = []
exclude_unchanged = true
log = "air.log"
delay = 1000 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500 # ms

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
